Feature/ZV-222 service registry
ZveronHSE/backend_new pull request #10
Opened 2023-01-05 22:51 UTC by Schuyweiz

безопасность и все вот это пока предлагаю не трогать
1. Пока не на чем тыкать
2. ставить всякие конфиги секьюрити в начале проекта би лайк 
![image](https://user-images.githubusercontent.com/57765462/210895193-3fe1dbeb-e8b5-47cb-ac35-01779a31814a.png)

2023-01-05 23:37 UTC, Schuyweiz commented on README.md
> +## CI / CD / Deploy
хер знает как оно сюда попало

2023-01-06 12:46 UTC, dakochik commented on build.gradle.kts
> +        }
Предлагаю такие изменения:
```suggestion
        implementation("org.springframework.boot:spring-boot-starter-web")
        if (project.name != "service_registry"){
            implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client:$eurekaVer")
            implementation("net.devh:grpc-spring-boot-starter:$grpcSpringBootStarter")
        }
```

1. Убрал webflux и netty, ничего не изменилось. Они точно нужны?
2. Grpc адаптация спринга для регистри не нужна

2023-01-06 12:46 UTC, dakochik commented on service_registry/build.gradle.kts
> +tasks.withType<Test> {
Можно убрать, есть в основном `build.gradle.kts`

2023-01-06 12:46 UTC, dakochik commented on service_registry/README.md
> +```
Возможно, было бы неплохо добавить минимальный пример использования сервиса:
```kotlin
class WhateverService {

    @GrpcClient("whatever-service")
    lateinit var service: WhateverServiceGrpcKt.WhateverServiceCoroutineStub

    suspend fun get() = service.get()
}
```
Это так должно выглядеть?

2023-01-06 16:09 UTC, WolfAlm requested changes

2023-01-06 16:09 UTC, WolfAlm commented on README.md
> +## CI / CD / Deploy
прочисти плз, чтобы не было дублирования

2023-01-06 16:09 UTC, WolfAlm commented on build.gradle.kts
> +        implementation("net.devh:grpc-spring-boot-starter:$grpcSpringBootStarter")
а толку, если это единственный раз используется? зачем в переменную выносить?

2023-01-06 16:09 UTC, WolfAlm commented on gradle.properties
> +eurekaVer=3.1.4
давай как у остальных переменных - Version

2023-01-06 16:09 UTC, WolfAlm commented on service_registry/build.gradle.kts
> +tasks.withType<Test> {
поддерживаю

2023-01-06 16:09 UTC, WolfAlm commented on build.gradle.kts
> +        implementation("org.springframework.boot:spring-boot-starter-web")
если эти зависимости нужные только для eureka, то зачем они в общем градле находятся?

2023-01-06 16:09 UTC, WolfAlm commented on service_registry/build.gradle.kts
> +    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:3.1.4")
давай поднимем до 4.0.0, предлагает такую версию, или там конфликты?

2023-01-06 16:09 UTC, WolfAlm commented on service_registry/README.md
> +```
да, было бы здорово иметь пример красивый

2023-01-06 16:09 UTC, WolfAlm commented on service_registry/src/main/resources/application.yml
> +    username: zveron_user
ты же вроде в качестве исключения добавлял так, чтобы не было проверки на наличие датасурса и прочее

2023-01-06 16:09 UTC, WolfAlm commented on build.gradle.kts
> +        implementation("io.netty:netty-resolver-dns-native-macos:4.1.86.Final:osx-aarch_64")
сделай тогда проверку на то, что если макось на м1 -- то скачивать зависимость

2023-01-06 16:09 UTC, WolfAlm commented on build.gradle.kts
> +        implementation("io.netty:netty-resolver-dns-native-macos:4.1.86.Final:osx-aarch_64")
```suggestion
if (osdetector.os.equals("osx")) {
    implementation("io.netty:netty-resolver-dns-native-macos::osx-x86_64")
    implementation("io.netty:netty-resolver-dns-native-macos::osx-aarch_64")
}
```

2023-01-06 16:09 UTC, WolfAlm commented on build.gradle.kts
> +        implementation("io.netty:netty-resolver-dns-native-macos:4.1.86.Final:osx-aarch_64")
версии забыла прописать но ладно

2023-01-06 22:39 UTC, Schuyweiz commented on README.md
> +## CI / CD / Deploy
И не будет, оно просто либо в одном либо в другом коммите полетит

2023-01-06 22:43 UTC, Schuyweiz commented on service_registry/build.gradle.kts
> +    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-server:3.1.4")
Там нужен спринг бут 3.0

2023-01-07 09:07 UTC, Schuyweiz commented on build.gradle.kts
> +        implementation("org.springframework.boot:spring-boot-starter-web")
потому что все сервисы будут пользоваться эврикой

2023-01-07 09:10 UTC, Schuyweiz commented on service_registry/src/main/resources/application.yml
> +    username: zveron_user
проще было вырубить ликвибейз в проекте

2023-01-07 13:51 UTC, Schuyweiz commented on build.gradle.kts
> +        }
1 - тут короче будет небольшая правка в доку, чтобы все клиенты эврики пользовались вебклиентом, тогда да, нужна либа вебклиента, чтобы его создать для запроса в эврику и нужен реатор нетти, чтобы получить коннект к эврике по запросу (иначе приложение не лажанется, но не зарегается)

2 - согл

2023-01-07 14:36 UTC, Schuyweiz commented on README.md
> +## CI / CD / Deploy
ладно убрал

2023-01-07 14:36 UTC, Schuyweiz commented on build.gradle.kts
> +        implementation("net.devh:grpc-spring-boot-starter:$grpcSpringBootStarter")
уже не помню что была за мысль, убрал обратно)

2023-01-07 14:36 UTC, Schuyweiz commented on build.gradle.kts
> +        implementation("io.netty:netty-resolver-dns-native-macos:4.1.86.Final:osx-aarch_64")
поправил

2023-01-07 14:36 UTC, Schuyweiz commented on gradle.properties
> +eurekaVer=3.1.4
поправил

2023-01-07 14:36 UTC, Schuyweiz commented on service_registry/README.md
> +```
не совсем красивый, но приемлимый пример есть теперь

2023-01-07 14:36 UTC, Schuyweiz commented on service_registry/build.gradle.kts
> +tasks.withType<Test> {
убрал

2023-01-07 14:45 UTC, WolfAlm approved these changes

2023-01-08 19:49 UTC, merged