[ZV-185] Сервис Profile
ZveronHSE/backend_new pull request #13
Opened 2023-01-23 13:56 UTC by dakochik

2023-01-24 21:36 UTC, WolfAlm commented on address_service/src/main/resources/application.yml
> +    port: 6565
```suggestion
    port: 0
```

пусть будет рандом

2023-01-24 21:36 UTC, WolfAlm commented on address_service/src/main/resources/application.yml
> +  port: 7565
```suggestion
    port: 0
```

пусть будет рандом

2023-01-24 21:36 UTC, WolfAlm commented on blacklist_service/src/main/resources/application.yml
> +  port: 7566
```suggestion
  port: 0
```

2023-01-24 21:36 UTC, WolfAlm commented on blacklist_service/src/main/resources/application.yml
>      port: 6566
```suggestion
     port: 0
```

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/resources/db/changelog/01_autogenerated.sql
> +    name       VARCHAR(255) NOT NULL,
можно до 50 уменьшить

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/resources/db/changelog/01_autogenerated.sql
> +    surname    VARCHAR(255) NOT NULL,
можно до 50 уменьшить

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/resources/db/changelog/01_autogenerated.sql
> +    phone            VARCHAR(255),
до 8 уменьшить?

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/exception/ProfileException.kt
> +open class ProfileException(override val message: String?): RuntimeException(message)
предлагаю так не делать, а брать по примеру как у меня:
```suggestion
import io.grpc.Status

open class ProfileException(status: Status, override val message: String?): RuntimeException(message)
```

Таким образом ты можешь в GrpcAdvice логику расписать типа такой: 
```
    @GrpcExceptionHandler(CategoryException::class)
    fun handleCategoryException(e: CategoryException): Status {
        logger.error { e.message }

        return e.status.withDescription(e.message)
    }
```

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/exception/ProfileException.kt
> +open class ProfileException(override val message: String?): RuntimeException(message)
то есть, прокидываются любые статусы, а не только захаркодженные Internal

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/exception/ProfileNotFoundException.kt
> +class ProfileNotFoundException(override val message: String) : ProfileException(message)
см выше

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/mapper/AddressMapper.kt
> +    fun address2Request(address: Address) = addressRequest {
а почему не Address.toRequest?

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/api/address/AddressService.kt
> +interface AddressService {
так ли нужны интерфейсы вообще?

2023-01-24 21:36 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/api/blakclist/BlacklistGrpsService.kt
> +class BlacklistGrpsService : BlacklistService {
скорее BlacklistGrpcClient

2023-01-25 18:03 UTC, dakochik commented on address_service/src/main/resources/application.yml
> +    port: 6565
Думаю возникнут сложности со сборкой докер образов

2023-01-25 18:40 UTC, Schuyweiz requested changes

2023-01-25 18:40 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/domain/ChannelsDTO.kt
> +data class ChannelsDTO(
давай везде будем единообразно использовать camel case

2023-01-25 18:40 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/domain/ChannelsDTO.kt
> +    var gmail: Boolean = false,
я правильно понимаю, что если/когда мы добавим условный mail.ru то у нас появится новое поле

2023-01-25 18:40 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/repository/ContactRepository.kt
> +    fun findByPhone(phone: String): Optional<Contact>
почему не CrudRepository?

почему optional, а не `Contract?`

2023-01-25 18:40 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/api/profile/ProfileServiceInternal.kt
> +        Empty.getDefaultInstance().also {
мне не очень нравится как эта строка читается. Типа мы возвращаем этот объект, **а так же** выполняем всю бизнес логику метода
Как мне кажется возвращаемый объект должен показывать, что мы успешно выполнили бизнес логику и завершаем выполнение метода

2023-01-25 18:40 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/validation/ContactsValidator.kt
> +        val numberOfSelectedWays = arrayOf(phone, vk, gmail, chat).count { it }
мб `numberOfSelectedChannels`?

2023-01-27 16:37 UTC, dakochik commented on profile_service/src/main/resources/db/changelog/01_autogenerated.sql
> +    phone            VARCHAR(255),
до 10, без кода? почему 8?

2023-01-27 21:13 UTC, closed without merging