[ZV-185] Сервис Profile
ZveronHSE/backend_new pull request #16
Opened 2023-01-27 21:12 UTC by dakochik

Тот же PR https://github.com/ZveronHSE/backend_new/pull/13 но пофикшенный

2023-01-27 21:39 UTC, Schuyweiz requested changes

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/ContactService.kt
> +    fun save(contact: Contact) = repository.save(contact)
зачем? Тут же и юзается, может просто репу вызовем

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/ContactService.kt
> +    fun findByChannelOrThrow(channelType: ChannelType, id: String): Contact = when (channelType) {
выглдяит как приватный метод

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +    fun deleteById(id: Long) = profileRepository.deleteById(id)
только тут юзается, давай напрямую звать репозиторий где надо

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +        if (request.authorizedProfileId == 0L || !blacklistClient.existsInBlacklist(
это два запроса тоже можно асинком

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +package ru.zveron.service
азчем такой сожный логгер, когда есть KLogging()

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/SettingsService.kt
> +    private fun findByIdOrThrow(id: Long) =
приватный метод вниз

2023-01-27 21:39 UTC, Schuyweiz commented on profile_service/src/main/resources/application.yml
> +    enabled: true
```suggestion
    enabled: true
  instance:
    metadata-map:
      ProfileServiceInternal: 'profile_internal.proto'
      ProfileServiceExternal: 'profile_external.proto'    

```

2023-01-27 22:56 UTC, dakochik commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +    fun deleteById(id: Long) = profileRepository.deleteById(id)
Еще в `ProfileServiceExternal`, остальное поправил, спасибо

2023-01-27 23:47 UTC, WolfAlm commented on profile_service/src/main/resources/application.yml
> +    enabled: true
просто external же

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/entity/Profile.kt
> +    @Column(nullable = false)
разве фолс? если онлайн -- то это налл, нет?

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/exception/ProfileNotFoundException.kt
> +class ProfileNotFoundException(override val message: String, code: Status.Code) : ProfileException(message, code)
этот класс наверное уже не нужен?

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/mapper/LotsMapper.kt
> +    fun List<Lot>.toBuilder(status: LotStatus): Collection<LotSummary> =
```suggestion
    fun List<Lot>.toBuilder(status: LotStatus): List<LotSummary> =
```
Хотя наверное непринципиально

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/resources/application.yml
> +      ProfileServiceInternal: 'profile_internal.proto'
```suggestion
```

апигетвею же не нужно об этом знать

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +        val profile = findByIdOrThrow(request.requestedProfileId)
это точно нужно первым ставить в строке, если не нашелся профиль, то нет смысла вообще пока дергать других сервисов

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +        val responseBuilder = GetProfilePageResponse.newBuilder().apply {
```suggestion
        val response= getProfilePageResponse {
```

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +            }
Вот слушай, что думаешь вообще насчет того, чтобы не размазывать добавление полей в билдер по всему методу, когда можно собрать все-все ответы, а потом передать в buildResponse()? 

Можешь посмотреть по примеру, как у меня сделано вот тут: https://github.com/ZveronHSE/backend_new/pull/17/files#diff-19d14c4054b0caf7057edf9ede1d8e8cd13049993ca5d18b0ff4b3460c013718R43  (если не перенаправит, то это в классе LotExternal  в методе createLot 

Там суть в том, что собираю всех клиентов, жду ответов от всех клиентов, а потом сохраняю сущность в сервисе, а потом и через мой самописный билдер -- собираю ответ

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +            }
логика, вероятно, станет более прозрачной: 
- сразу в одном месте видишь билдеры
- трай кетчи не придется трижды писать(кстати об этом -- эту логику можно вынести к клиентам, чтобы не было просто request/response)

2023-01-28 11:57 UTC, WolfAlm commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +            }
И не нужно будет делать типа newBuilder, build и всякие apply

2023-01-28 17:35 UTC, dakochik commented on profile_service/src/main/kotlin/ru/zveron/entity/Profile.kt
> +    @Column(nullable = false)
Зависит от того, как мы его обновление реализуем, пока предлагаю не заострять на этом внимание

2023-01-28 17:41 UTC, dakochik commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +        val profile = findByIdOrThrow(request.requestedProfileId)
Но тогда нет смысла параллелить запрос к черному списку, т.к. маппинг сущностей времени практически не занимает. В то же время кейс, когда id профиля некорректен, мне кажется, должен редко встречаться, так что мы должны выигрывать от такой последвоательности

2023-01-28 17:44 UTC, dakochik commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +        val responseBuilder = GetProfilePageResponse.newBuilder().apply {
Все поля в генерируемых сущностях неизменяемые, а мне нужно в `addAdditionalFields()` дописывать значения, поэтому тут билдер. Можно сначала получить поля и сделать для них дефолтные значения в тех случаях, когда их надо пропустить, но это будет выглядеть более громоздко

2023-01-28 20:05 UTC, WolfAlm approved these changes

2023-01-28 20:54 UTC, Schuyweiz approved these changes

2023-01-28 20:54 UTC, Schuyweiz commented on profile_service/src/main/kotlin/ru/zveron/service/ProfileService.kt
> +        val addExtraFields = !blacklistCoroutine.awaitBlacklistResponse()
мы по сути не выполняем эту штуку асинхронно с остальными запросами. Минор, но как варинт можно было именно этот метод вызывать через withContext как мне кажется

2023-01-28 21:43 UTC, merged