[ZV-186] Lot Service
ZveronHSE/backend_new pull request #17
Opened 2023-01-27 22:11 UTC by WolfAlm

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/LotServiceApplication.kt
> +@SpringBootApplication
Нужен `@EnableEurekaClient`, потому что этот сервис будет дергать профиль

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/client/address/AddressClient.kt
> +            address.region?.let { region = it }
разве в protobuf строки бывают nullable?

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        }
А это точно асинхронно выполнится?
В таком тесте все последовательно идет:
```
    @Test
    fun simpleTest() = runBlocking {
        coroutineScope {
            async {
                println("strart")
                delay(5000)
                println("end")
            }
        }
        println("sdfdsf")
        val x = 3
        println("done")
    }
```

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        // TODO подумать как тут лучше сделать(реально ли запускать в любом случае, ибо может быть ряд ошибок ниже
`@Transactional` тут не поможет, чтобы если что откатить инкремент?

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +                }.also { it.start() }
зачем писать `start`? она же и так запускается сразу

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +                lotFavoriteClient.checkLotsInFavorite(lots.map { it.id }, request.id)
вот вопрос: у нас метадата шерится между сервисами? то есть если профиль дернул объявления, и профиль знает Id авторизованного пользователя, узнает ли его дергаемые объявления? если да, то тут надо поставить заглушку - id авторизованного пользователя вместо `request.id`, чтобы не забыть потом поменять на реальный. Если нет, то нужно подправить контракт и соответсвующее поле, а я внесу правки в вызов со стороны профиля

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/repository/LotParameterRepository.kt
> +@Repository
```suggestion
```

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/repository/LotPhotoRepository.kt
> +@Repository
```suggestion
```

2023-02-03 18:58 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +    private fun validateRequestForUpdating(
Раз это используется не только в обновлении, но и в создании
```suggestion
    private fun validateLotProperties(
```

2023-02-05 10:38 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/client/address/AddressClient.kt
> +            address.region?.let { region = it }
это entity) переименую, чтобы не путаться

2023-02-05 10:42 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/client/address/AddressClient.kt
> +            address.region?.let { region = it }
да, не бывают, я перепутала с entity

```
            address.takeIf { it.hasRegion() }?.let { region = it.region }
            address.takeIf { it.hasDistrict() }?.let { district = it.district }
            address.takeIf { it.hasTown() }?.let { town = it.town }
```

2023-02-05 10:53 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +                lotFavoriteClient.checkLotsInFavorite(lots.map { it.id }, request.id)
не шерится, как обсудили 


я только не поняла, где тут нужно именно править в контракте, если я передаю и так userId и получаю userId от тебя

2023-02-05 11:02 UTC, dakochik commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +                lotFavoriteClient.checkLotsInFavorite(lots.map { it.id }, request.id)
нужно добавить в контракт объявлений поле - айдишник авторизованного пользователя, чтобы понимать, кто просматривает объявления, которые ты возвращаешь. понимать это нужно чтобы корректно подкрашивать отметку о том, что объявления находится / не находится в избранном. Когда добавишь тегни пж меня и я в этом же пр поменяю логику в профиле, чтобы ничего не сломалось в мастере

2023-02-05 11:18 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +                lotFavoriteClient.checkLotsInFavorite(lots.map { it.id }, request.id)
поняла свой косяк, поправим ща

2023-02-08 20:40 UTC, Schuyweiz requested changes

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/build.gradle.kts
> +    testImplementation("com.ninja-squad:springmockk:4.0.0")
кажется что мы этим все пользуемся, если подтянуть дев, то там уже должна быть эта зависимость в рутовом градле

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/build.gradle.kts
> +    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.0")
думаю можно версию в проперти протащить, уже как минимум в 3х модулях будет использоваться

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/LotServiceApplication.kt
> +@SpringBootApplication
я кстати потыкался, вроде бы и не нужен, по дефолту проперти `eureka.client.enabled=true`

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +        return response.isExistsList[0]
без доки не понятно почему там массив и почему берем 0-й элемент

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +        return response.isExistsList[0]
а понял, это типа список лотов, которые существуют

а почему мы сделали лист из булей? Кажется, что возвращать айдишники тех, кто существует было интуитивнее

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +    suspend fun checkLotInFavorite(lotId: Long, userId: Long): Boolean {
в нейминге нужен `IS` хоть где-то тк с булями работаем

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/parameter/ParameterClient.kt
> +            if (ex.status.code == Status.INVALID_ARGUMENT.code) {
Все же статусы у грпц хуйня кажется и придется в метадату свои какие-то статусы наверное имплементить

Мне вот не очевидно по `INVALID_ARGUMENT` что что-то не так с параметрами по бизнес логике, а не что в запрос к клиенту не то положили и он не смог это переварить

`Client specified an invalid argument. Note that this differs from FAILED_PRECONDITION. INVALID_ARGUMENT indicates arguments that are problematic regardless of the state of the system (e.g., a malformed file name)`

И вот кажется, что `FAILED_PRECONDITION` больше подходит, так как я понимаю состояние системы влияет на успех параметров

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/entity/Lot.kt
> +    var id: Long = -1,
а почему это все `var`? По другому не работает?

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/entity/Lot.kt
> +    var gender: Gender? = null,
не так много экономим по памяти, но при этом -читабельность в бд кмк

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/exception/util/ValidateValue.kt
> +object ValidateValue {
я бы назвал `ValidationUtils`

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/exception/util/ValidateValue.kt
> +    fun Long.isPositive(nameField: String) {
и тут наверное `validatePositive` потому что `isPositive` все же подразумевает, что возвращается буль

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return cardLotBuilder {
не интуитивное название. Я вижу возвращаем мы `CardLot` но при этом тут почему-то билдер и это малость конфузит

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return cardLotBuilder {
более того если метод или класс имеет в названии `Builder` кажется логичным, что чтобы получить объект, нужно вызвать `build`

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return empty { }
минор, может `Empty.getDefaultInstance()`?

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +            async {
тут `launch` тк не нужен результат

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        if (request.sortCase == WaterfallRequest.SortCase.SORT_NOT_SET) {
не совсем в ресурсе, но разве нету какого-то дефолта, с которым можно что-то вернуть? Чтобы не падать

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +            val lots = lotService.getLotsByIds(request.lotIdsList)
как я понимаю, ты здесь хочешь асинхронно сходить в бд, для этого, тут тоже бы надо async

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +            return lotsIdResponse { }
```suggestion
            return LotsIdResponse.getDefaultInstance()
```

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/CardLotBuilder.kt
> +        if (lot == null) {
зачем тогда его вообще делать nullable?

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/CardLotBuilder.kt
> +class CardLotBuilder(
это точно нужно? выглядит как второй конструктор для лота

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/CardLotBuilder.kt
> +            }
все вот это некрасивое бы в отдельные методы спрятать, и так понятно, что они просто поля маппят, но глаз замыливает очень кмк

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/ConditionsParser.kt
> +package ru.zveron.mapper
кажется что парсер, это скорее вспомогательный инструмент, нежели маппер, то есть место ему в `util` папке

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/ConditionsParser.kt
> +object ConditionsParser {
потому прочитал весь класс и похоже, что скорее класс нужно переименовать, это не парсер, это скорее маппер кмк

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/LotMapper.kt
> +        val lastLot = summaryLots[summaryLots.size - 1]
```suggestion
        val lastLot = summaryLots.last()
```

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/LotMapper.kt
> +    private fun Instant.toFormattingDate() = date.format(Date.from(this))
приватный метод вниз

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/exception/util/ValidateValue.kt
> +package ru.zveron.exception.util
это не вспомогательное средство для ошибок, это вспомогательно средство в рамках всего приложения, по моему ему место в папке `util`

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/SellerMapper.kt
> +                else -> {}
тут разве не должна быть ошибка, что если прилетело что-то, чего мы не ожидаем по when, то это `INVALID_ARGUMENT`

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/Address.kt
> +    // Отформатированный адрес
отформатированный в какой формат?

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/ChannelType.kt
> +    var phone: Boolean = false,
були бе префикса `is` очень сложно читается

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/SellerProfile.kt
> +    val contact: ChannelType,
селлер не может быть без картинки?

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/SellerProfile.kt
> +    val lastSeen: Boolean
почему `lastSeen` это буль? Выглядит как `isOnline` судя по тому как ты хочешь это использовать потом

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/SummaryLot.kt
> +    val dateCreation: Instant,
возможно вопрос вкусовщины, но кмк `createdAt` звучит лучше

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/constant/Gender.kt
> +package ru.zveron.model.constant
не совсем вижу логику по которой енам должен быть в пакете константы, а не в пакете модели

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/repository/LotStatisticsRepository.kt
> +    @Query("UPDATE LotStatistics l set l.quantityView = l.quantityView + 1 WHERE l.id = ?1")
давай параметры через их имена вставлять, то есть `:id` так проще читается

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +    @Transactional
одна операция `save`, зачем

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +        return lotRepository.saveAndFlush(lot)
зачем `saveAndFlush`

2023-02-08 20:40 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/service/LotStatisticsService.kt
> +    @Transactional
кажется, что это лишнее

2023-02-09 19:44 UTC, WolfAlm commented on lot_service/build.gradle.kts
> +    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.0")
нет особо смысла, тк все же это три модули, а не все модули

2023-02-09 19:47 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +        return response.isExistsList[0]
не, мы передаем список айдишников, и сообственно я получаю список булевых, которые сохранили порядок, и я знаю, что например, для первого объявления это true

Почему не назад списком айдишником -- все равно нужно будет тогда искать по множеству, есть ли такой айдишник или нет 

почему берем 0-й элемент - есть у меня 2 кейса:
1. Лента объявлений - там мне нужно передавать "батчем" список айдишников, где собственно и нужно получать инфу, какие объявления в избранном
2. Карточка товара - тут мне тогда достаточно просто передать 1 айдишник и получить собственно один ответ) (поэтому первый элемент) напишу комментом

2023-02-09 19:51 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/client/parameter/ParameterClient.kt
> +            if (ex.status.code == Status.INVALID_ARGUMENT.code) {
1. Это скорее особенность реализации конкретного сервиса, что условно они договорились возвращать INVALID_ARGUMENT, где будут описывать свою ошибку и которую в целом можно прокидвыать вверх, поэтому и тут сделала такую логику. INVALID_ARGUMENT система сама не бросит
2. Не подходит FAILED_PRECONDITION - потому что это пользак долбалеб и он чет не то указал  и мы собственно сообщаем об этом

2023-02-09 19:53 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/entity/Lot.kt
> +    var id: Long = -1,
поправила

2023-02-09 19:55 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/entity/Lot.kt
> +    var id: Long = -1,
По большей части из-за того, чтобы мне было удобно изменять у существующей сущности и сохранять ее с новыми параметрами, например так: 

```
 with(lot) {
            title = request.title
            description = request.description
            price = request.price
            channelType = request.communicationChannelList.toChannelType()
            parameters = request.parametersMap.map {
                LotParameter(
                    id = LotParameter.LotParameterKey(it.key, lot.id),
                    value = it.value,
                    lot = lot
                )
            }
            photos = request.photosList.map {
                LotPhoto(
                    lot = lot,
                    imageId = it.id,
                    order = it.order
                )
            }
        }
```

2023-02-09 19:59 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return empty { }
мне не оч нравится такое, выглядит очень джавно

2023-02-09 19:59 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        if (request.sortCase == WaterfallRequest.SortCase.SORT_NOT_SET) {
не, пусть мобильщики сами переделают свой хуевый запрос извините)))

2023-02-09 20:00 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +            val lots = lotService.getLotsByIds(request.lotIdsList)
а я тут не стала делать так, тк короутина выше и так уже асинхронно запустилась, поэтому пока я жду тут, та корутина либо завершит, либо я буду тоже ждать ее и уже зайду в метод со всеми значениями

я не права?

2023-02-09 20:01 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +            return lotsIdResponse { }
см выше почему я не стала так делать

2023-02-09 20:01 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/mapper/LotMapper.kt
> +        val lastLot = summaryLots[summaryLots.size - 1]
красивое, не знала об этом

2023-02-09 20:04 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/mapper/SellerMapper.kt
> +                else -> {}
ну я тут не стала такую логику делать, потому что мы просто тупо не поддержали это условно у себя, и если от профиля придет такой запрос мол, смотрите, мы тут сделали новый канал. Поддержите плз

то мы тут добавим еще одну такую штуку)

2023-02-09 20:05 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/model/ChannelType.kt
> +    var phone: Boolean = false,
вот тут интересный вопрос, потому что меня юрец задушил за то, что не нужно нахуй is для булевых, если знаем что оно и так булево

а ты что думаешь?

2023-02-09 20:06 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/model/SellerProfile.kt
> +    val contact: ChannelType,
не может, там по дефолту либо стандартная картинка(ей зарезервирована в виде id = 1), либо какая-нить своя)

2023-02-09 20:06 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/model/SellerProfile.kt
> +    val lastSeen: Boolean
да, раньше там был Instant, потом забыла поправить, спасибо!

2023-02-09 20:08 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/model/SummaryLot.kt
> +    val dateCreation: Instant,
да, вопрос вкусовщины

2023-02-09 20:09 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/model/constant/Gender.kt
> +package ru.zveron.model.constant
енам это не набор констант?)

2023-02-09 20:10 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +    @Transactional
а там вроде как будет скопом сохраняться для LotStatistics, LotPhoto и тд, поэтому так сделала

2023-02-09 20:10 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +        return lotRepository.saveAndFlush(lot)
это наследие из старого кода, без него не работало, не помню почему

2023-02-09 20:13 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return cardLotBuilder {
это прикол dsl, что они всегда в конце вызовут build, если я верну в cardLot -- будет конфликт с существующим контрактным названием

почему builder -- потому что по факту там под капотом передаешь какие-то параметры, а там собирается целая сущность cardLot из этих больших параметров

2023-02-09 23:06 UTC, Schuyweiz commented on lot_service/build.gradle.kts
> +    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.0")
Так версию, а не саму либу

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +        return response.isExistsList[0]
Почему не назад списком айдишником -- все равно нужно будет тогда искать по множеству, есть ли такой айдишник или нет

Но читаться будет гораздо лучше. 
И звучит как настоящий ад для дебага/чтения логов

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/parameter/ParameterClient.kt
> +            if (ex.status.code == Status.INVALID_ARGUMENT.code) {
Ну в смысле они договорились, `INVALID_ARGUMENT` не подходит как раз таки по причине того, что ты во втором пункте и пишешь, эта ошибка говорит о том, что пользак долбаеб и что-то не то ввел

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return cardLotBuilder {
тогда предлагаю не использовать dsl, это очень плохо читается

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        if (request.sortCase == WaterfallRequest.SortCase.SORT_NOT_SET) {
по моему это не совсем правильное поведение системы. Мы не должны падать на сортировке
Это не мобильщики будут переделывать запрос, а пользователь, как я понимаю. Я бы не очень кайфовал с "что-то пошло не так" из-за неправильного запроса на сортировку в маркетплейсе

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/mapper/SellerMapper.kt
> +                else -> {}
Я считаю здесь все же лчше поддержать такое поведение, чтобы оно было fail-fast в случае если все же мы что-то у себя не поддержали, а сервис что-то новое прислал. Если отойти от контекста, то защита от дурака. Лучше у меня при тестах упадет приложение, чем невнимательный тестировщик не увидит, что не хватает нового канала связи и оно поедет в прод, я так для себя это вижу

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +    @Transactional
метод `save` в jpa по дефолту транзакционный как я помню, все что там внутри будет твориться, хибер вроде как должен в одну транзакцию и сам поместить. Мне так кажется

2023-02-09 23:41 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/service/LotService.kt
> +        return lotRepository.saveAndFlush(lot)
убрать и посмотреть почему оно без него может не работать сейчас? :D

2023-02-10 11:22 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/entity/Lot.kt
> +    var id: Long = -1,
Для этого у data классов есть copy

2023-02-10 11:55 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/ChannelType.kt
> +    var phone: Boolean = false,
Интересно какой аргумент почему так делать не надо. 

Аргумент почему надо простой, точнее их несколько
- Java Beans spec (да, котлин не жавка, но многие спеки и конвенции жавки применимы к котла)
- Звучит как нормальное предлодение, составленное человеческим языком. Есть объект, у него есть поле допустим isActive, ты спрашиваешь "этот объект активен?" Т.е. "Is (this field) active?"
- В жавке еще можно сказать, что вот булево поле без префикса, а вот получать его мы будет через isXXX геттер, но в котле если не переопределять, то это поле и есть твой геттер

2023-02-10 11:56 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/SummaryLot.kt
> +    val dateCreation: Instant,
'dateCreation' звучит не по английски еще
По сути переводится "создание даты", звучит как процесс, а не как свойство 
Так что нужно менять

2023-02-10 11:57 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/model/constant/Gender.kt
> +package ru.zveron.model.constant
Ну так то да, но вот почему тогда не назвать папку enum например?

2023-02-10 12:56 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotInternalController.kt
> +            val lots = lotService.getLotsByIds(request.lotIdsList)
Не могу тут дать теоретически правильный ответ)
Я скорее просто иду по эмпирическому правилу, что если 2+ операции нужно исполнить параллельно, то бахнуть обе в асинк

Можно попробовать в логах посмотреть в какой корутине обе операции исполняются.

Просто запрос в бд блокирующая операция например, так что хз даже, будет ли работать тут асинк и вовсе. Для блокирующей если ее отправить в Dispatchers.IO должна.
Но типа она блокает тред от котрого корутина отпочковалась... короче хз, нужно ставить логи и смотреть глазами кажется

2023-02-11 18:59 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/model/constant/Gender.kt
> +package ru.zveron.model.constant
<img width="213" alt="image" src="https://user-images.githubusercontent.com/60275667/218276245-0b109abe-d2db-4203-9341-e42e2b0677ea.png">
если назвать как enum, то кстати почему-то идеа перестает его видеть как модуль

2023-02-11 19:01 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        if (request.sortCase == WaterfallRequest.SortCase.SORT_NOT_SET) {
суть в том, что должна быть хотя бы любая сортировка, и собственно, апи ждет любую установленную сортировку, и когда ты открываешь ленту любого маркетплейса, ты увидишь, что там есть перечень сортировок и по умолчанию всегда выбрана какая-нить сортировка

и собственно, поэтому и пользак не дойдет до этого сценария, когда не выбрана ни одна)

2023-02-11 19:02 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/mapper/SellerMapper.kt
> +                else -> {}
просто это такая штука, где не должна падать приложение, ну нет контактов ну и хуй с ним собственно. упадет в другом месте

2023-02-11 19:15 UTC, WolfAlm commented on lot_service/build.gradle.kts
> +    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.14.0")
я тоже про версию говорю) если либа только внутри модуля живет, то и пусть версия тоже вместе с ней живет)

2023-02-11 19:16 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/entity/Lot.kt
> +    var id: Long = -1,
ну это нужно создавать новую сущность и тд, а потом и инициализировать такие поля, мне не оч удобно так

2023-02-11 19:16 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/grpc/LotExternalController.kt
> +        return cardLotBuilder {
не, мне dsl оч удобен и я его переиспользую с разными параметрами 

переименовала в buildCardLot

2023-02-11 19:17 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/mapper/CardLotBuilder.kt
> +        if (lot == null) {
в силу особенностей dsl

2023-02-11 19:17 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/mapper/CardLotBuilder.kt
> +class CardLotBuilder(
мне для удобства маппинга

2023-02-12 13:31 UTC, WolfAlm commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +        return response.isExistsList[0]
можно будет потом переделать, так-то справедливое замечание

2023-02-12 15:51 UTC, Schuyweiz commented on lot_service/src/main/kotlin/ru/zveron/client/favorite/LotFavoriteClient.kt
> +        return response.isExistsList[0]
только тогда задачу заведи)

2023-02-12 16:06 UTC, Schuyweiz approved these changes

2023-02-12 16:06 UTC, Schuyweiz commented on lot_service/src/test/kotlin/ru/zveron/mapper/ConditionsMapperTest.kt
> +        conditionsSearch.parameters.shouldNotBeNull()
на будущее можно линковать `shouldBeNotNull().asClue`

2023-02-12 17:21 UTC, merged