[ZV-297] apigw auth integration
ZveronHSE/backend_new pull request #27
Opened 2023-02-05 19:55 UTC by Schuyweiz

2023-02-10 16:12 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/config/AuthGrpcClientConfig.kt
> +    fun authClient(authService: AuthServiceGrpcKt.AuthServiceCoroutineStub) = GrpcAuthClient(client = authService)
если тут поменять на authService в названии метода, тогда сверху не нужно будет писать beanname = authService

2023-02-10 16:12 UTC, WolfAlm commented on apigateway/src/main/resources/db/data/aliases.csv
> +"parameterValidate","parameter-service","CategoryService","validateValuesForParameters","BUYER"
```suggestion
"categoryGetChild","parameter-service","CategoryService","getChild","ANY"
"parameterGet","parameter-service","CategoryService","getParametersByCategory","ANY"
```

2023-02-10 16:12 UTC, WolfAlm commented on apigateway/src/main/resources/db/data/aliases.csv
> +"addressSave","address-service","AddressService","SaveAddressIfNotExists","BUYER"
```suggestion
```
не публичная штука

2023-02-10 16:12 UTC, WolfAlm commented on apigateway/src/main/resources/db/changelog/02_add_access_role.sql
> +--changeset Schuyweiz:access_role_init
ты реально не делаешь автоматическую генерацию?) реально улетная штука

2023-02-10 16:12 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/persistence/entity/MethodMetadata.kt
> +@Table("method_metadata")
а в чем прикол замены?

2023-02-10 16:32 UTC, WolfAlm requested changes

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/grpc/ApiGatewayMapper.kt
> +    }
```suggestion
    fun AccessScope.toScope() = when(this) {
        AccessScope.ANY -> ServiceScope.ANY
        AccessScope.BUYER -> ServiceScope.BUYER
        else -> error("Unknown access role type")
    }
```

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/grpc/service/ApiGatewayService.kt
> +        logger.debug(append("requestAlias", request.alias)) { "Handling gateway call request" }
у тебя это и так есть в контроллере? зачем дважды писать?

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/grpc/interceptor/AuthInterceptor.kt
> +        headers.get(accessTokenKey).let {
не ?.let{} ?

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/component/AuthResolver.kt
> +            return null
нужно все равно получать юзера, просто если не получил - то не бросать экспешн

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/utils/DescriptorsUtil.kt
> +        }
нет, давай так делать не будем, а то потом хуй поймем, кто виноват -- клиент не прислал, апигв перезатер, и прочее и прочее

давай в метаданные класть такие штуки, а из контрактов мы такие поля будем убирать

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/kotlin/ru/zveron/apigateway/utils/DescriptorsUtil.kt
> +        }
чтобы была разделена четко зона ответственностей - в боди кладет ТОЛЬКО клиент и никто больше, а в метаданных могут класть КТО УГОДНО

2023-02-10 16:32 UTC, WolfAlm commented on apigateway/src/main/resources/application.yml
>    datasource:
а зачем сюда?

2023-02-10 16:57 UTC, Schuyweiz commented on apigateway/src/main/kotlin/ru/zveron/apigateway/config/AuthGrpcClientConfig.kt
> +    fun authClient(authService: AuthServiceGrpcKt.AuthServiceCoroutineStub) = GrpcAuthClient(client = authService)
я лучше буду так писать, потому что это все таки не сервис, а клиент инициируется

2023-02-10 16:57 UTC, Schuyweiz commented on apigateway/src/main/kotlin/ru/zveron/apigateway/grpc/interceptor/AuthInterceptor.kt
> +        headers.get(accessTokenKey).let {
токен наллабл сделал в контексте, все равно на этоп этапе ничего порешать с ним не сможем если его нет, тк нет инфы по сервисам

2023-02-10 16:57 UTC, Schuyweiz commented on apigateway/src/main/kotlin/ru/zveron/apigateway/persistence/entity/MethodMetadata.kt
> +@Table("method_metadata")
замены чего?

2023-02-10 16:57 UTC, Schuyweiz commented on apigateway/src/main/kotlin/ru/zveron/apigateway/utils/DescriptorsUtil.kt
> +        }
всмысле, это айдишник пользователя, мы же договорились не класть айдишник пользователя в метаданные, а прокидывать его в запрос

2023-02-10 16:57 UTC, Schuyweiz commented on apigateway/src/main/resources/application.yml
>    datasource:
чтобы миграции включить

до этого хуй пойми что происходило и конфиги datasource не триггерили миграцию

datasource убрать в той же задаче, где по человечески для r2dbc и jdbc сделаем развилку в скрипте

2023-02-10 16:57 UTC, Schuyweiz commented on apigateway/src/main/resources/db/changelog/02_add_access_role.sql
> +--changeset Schuyweiz:access_role_init
видел я там улетные названия констрейнтов, а еще улетно ловить по жопе ошибку, что таблица уже существует прыгая с ветки на ветку

плюс более вразумительное название ченжсета

2023-02-10 17:18 UTC, dakochik commented on apigateway/src/main/kotlin/ru/zveron/apigateway/component/constant/ServiceScope.kt
> +    BUYER,
имхо если  BUYER - авторизованный пользователь, то лучше назвать  AUTHORIZED, это же не обязательно покупатель, но и продавец, например

2023-02-10 17:18 UTC, dakochik commented on apigateway/src/main/resources/db/data/aliases.csv
> +"profileGetPage","profile-service","ProfileServiceExternal","GetProfilePage","BUYER"
```suggestion
"profileGetPage","profile-service","ProfileServiceExternal","GetProfilePage","ANY"
```

2023-02-10 17:52 UTC, Schuyweiz commented on apigateway/src/main/kotlin/ru/zveron/apigateway/component/constant/ServiceScope.kt
> +    BUYER,
я закладываюсь на то, что и селлер тоже будет иметь место быть и иметь ручки, строго только для него

2023-02-10 17:53 UTC, Schuyweiz commented on apigateway/src/main/kotlin/ru/zveron/apigateway/utils/DescriptorsUtil.kt
> +        }
порешали в телеге6 что в хедеры сложим

2023-02-10 18:17 UTC, Schuyweiz commented on apigateway/src/main/resources/db/changelog/02_add_access_role.sql
> +--changeset Schuyweiz:access_role_init
плюс это вроде всякие жпа аннотации, которыми я не пользуюсь

2023-02-11 18:48 UTC, WolfAlm approved these changes

2023-02-12 13:07 UTC, merged