[ZV-189] Микросервис Favorites
ZveronHSE/backend_new pull request #6
Opened 2023-01-01 23:30 UTC by dakochik

PR спеки: https://github.com/ZveronHSE/contract/pull/4

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/resources/db/changelog/01_autogenerated.sql
> +CREATE INDEX lots_statistics_index ON public.lots_favorites_counter (lot_id, shard_id);
порядок индекса играет роль, поэтому если у тебя была задумка сначала быстренько по шардам найти нужное, а потом уже искать объявления, то сначала нужно shard_id, а потом уже и lot_id

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/repository/LotsFavoritesCounterRepository.kt
> +    @Query("UPDATE LotsFavoritesCounter l SET l.counter = l.counter + 1 WHERE l.id.lotId = ?1 AND l.id.shardId = ?2")
тут порядок должен быть наоборот, составной индекс смотрит слева направо

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        if (!lotCounterRepository.existsById_LotId(request.favoriteLotId)) {
а почему тут мы не используем при проверке существования шард айди для более быстрого поиска, если ты его уж используешь?

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        lotCounterRepository.saveAll(List(SHARDS_NUMBER) { i ->
мне кажется, мы немного по разному понимаем шарды

Мое определение -- шарды это когда ты можешь распределять айдишники объявлений по разным БД(которые в свою очередь будут являться шардами, но тк мы ограничиваемся одним БД, мы различаем по шард айди). 

Собственно из этого вытекает то, что ты не сохраняешь в каждом шарде счетчик. 

И логика получается переделывается так - чтобы определить, в каком шарде хранить объявление, можно сделать логику по взятию остатка от ID объявления - lotId % SHARDS_NUMBER, и сохранять только в этом шарде

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        lotCounterRepository.saveAll(List(SHARDS_NUMBER) { i ->
или мы как-то по разному трактовали код...

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        lotCounterRepository.saveAll(List(SHARDS_NUMBER) { i ->
собственно, этого мне не хватает для ключевого понимания избранных объявлений, дальше комментить не буду, пока тут не разберемся

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            val exists = profileRepository.existsById(
мне для спортивного интереса - какой запрос там под капотом выполняется?

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            profileExistsInFavoritesResponse { profileExists = exists }
вот тут из-за того что в названии profileExistsInFavorites достаточно было в body isExists = exists. И таких моментов много 

но мб это моя придирка

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +        } ?: throw FavoritesException("Нельзя удалиться себя из своего списка избранного")
нельзя удалить себя или нельзя удалиться)

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +    override suspend fun listFavoriteProfiles(request: ListFavoriteProfilesRequest): ListFavoriteProfilesResponse =
list не нужен

достаточно favoriteProfiles

2023-01-02 22:58 UTC, WolfAlm commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +    override suspend fun listFavoriteProfiles(request: ListFavoriteProfilesRequest): ListFavoriteProfilesResponse =
ну или getFavoriteProfiles...

2023-01-03 09:25 UTC, dakochik commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        lotCounterRepository.saveAll(List(SHARDS_NUMBER) { i ->
Идея моего подхода была в том, чтобы уменьшить количество блокировок при обновлении счетчика. Например, у нас одновременно приходит 4 запроса на изменение счетчика. Если у нас одна запись отвечает за него, то все запросы выполняются поочереди. Если же одна запись описывается несколькими счетчиками, то в идеале эти запросы будут размазываться по всем счетчикам и блокировок будет меньше.

Возможно, о названии можно поспорить, но я исходил из той логики, что шарды БД - куски, которые содержат различную информацию и при этом они изначально являлись одной БД. Так и со счетчиками - несколько счетчиков содержат разную информацию, но при этом описывают статистику одного объявления

2023-01-03 09:30 UTC, dakochik commented on favorites_service/src/main/kotlin/ru/zveron/repository/LotsFavoritesCounterRepository.kt
> +    @Query("UPDATE LotsFavoritesCounter l SET l.counter = l.counter + 1 WHERE l.id.lotId = ?1 AND l.id.shardId = ?2")
ХМ, но у меня в индексе как раз сначала идет `lotId`, а потом `shardId`:
```
CREATE INDEX lots_statistics_index ON public.lots_favorites_counter (lot_id, shard_id);
```

2023-01-03 09:32 UTC, dakochik commented on favorites_service/src/main/resources/db/changelog/01_autogenerated.sql
> +CREATE INDEX lots_statistics_index ON public.lots_favorites_counter (lot_id, shard_id);
Я предполагаю, что селективность `lot_id` выше, чем `shard_id`, поэтому, как я понимаю, выгоднее в таком порядке составлять по ним индекс

2023-01-03 09:37 UTC, dakochik commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        if (!lotCounterRepository.existsById_LotId(request.favoriteLotId)) {
1. Тут мы хотим понять, есть ли шарды конкретного объявления, т.е. подходит любой шард объявления с конкретным Id. 
2. Если искать только по шарду, это не будет подходить, так как id шардов птовторяются (для любого объявления создаются 4 шарда с id 0...3). 
3. Если искать по id объявления + id любого шарда то такой вариант тоже подходит, но я подумал это дольше, чем просто по объявлению, ведь тогда мы будем проделывать дополнительную ненужную работу по поиску конкретного шарда среди шардов объявления, что нам не нужно (нужно знать что хоть один шард существует т.к. это означает что все остальные шарды также существуют)

2023-01-03 10:35 UTC, dakochik commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            val exists = profileRepository.existsById(
```
select count(*) as col_0_0_ 
from profiles_favorites_record profilesfa0_ 
where (profilesfa0_.favorite_user_id, profilesfa0_.owner_user_id)=(?, ?)
```

Получается тут в индексе надо столбцы поменять местами

2023-01-03 12:48 UTC, Schuyweiz requested changes

2023-01-03 12:48 UTC, Schuyweiz commented on favorites_service/src/main/kotlin/ru/zveron/service/LotsFavoritesService.kt
> +        lotCounterRepository.saveAll(List(SHARDS_NUMBER) { i ->
Думаю что это нужно убирать 

- шардирование нужно для решения работы с большой бд, а не с большим количеством запросов на обновление колонки кмк
- такой нагрузки пока нет, так что это кажется как overengineering 
- увеличение бд в 4 раза 
- Решение этой проблемы все еще не шардирование, а введение какой-нибудь очереди сообщений

2023-01-03 12:48 UTC, Schuyweiz commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            val exists = profileRepository.existsById(
А нельзя эту штуку зашить в какой-то констрент по бд?
может вот такое
`ALTER TABLE foo 
  ADD CONSTRAINT aa_cannot_be_equal_to_bb_CHK
    CHECK (aa <> bb) ;`

2023-01-03 12:48 UTC, Schuyweiz commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            favoriteProfiles.addAll(
addAll возвращает Unit, а ты вроде в ответе хочешь вернуть список

2023-01-03 13:02 UTC, dakochik commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            favoriteProfiles.addAll(
МБ я неправильно понял коммент, но `favoriteProfiles` - поле тела ответа, изменяемый список, в `listFavoriteProfilesResponse { ... }` я собираю ответ, инициализируя его поля. В качестве пруфов, что все норм, можно посмотреть тест `ListFavoriteProfiles When requests for favorite profiles Then appropriate profiles are returned`

2023-01-04 21:57 UTC, WolfAlm approved these changes

2023-01-04 21:57 UTC, WolfAlm commented on favorites_service/src/test/kotlin/ru/zveron/service/LotsFavoritesServiceTest.kt
> +            lotsFavoritesRecordRepository.findById(generateKey(profileId1, lotId1)).isPresent shouldBe true
**nit:** 
```suggestion
            lotsFavoritesRecordRepository.findById(generateKey(profileId1, lotId1)).isPresent.shouldBeTrue() 
```

2023-01-05 23:06 UTC, Schuyweiz commented on favorites_service/src/test/kotlin/ru/zveron/service/LotsFavoritesServiceTest.kt
> +            lotsFavoritesRecordRepository.findById(generateKey(profileId1, lotId1)).isPresent shouldBe true
мне кстати кажется этот вопрос стоит решить, чтобы единого кодстайла придерживались - будем ли абьюзить такой синтаксис или вызывать как метод через точку

2023-01-05 23:18 UTC, Schuyweiz commented on favorites_service/src/main/kotlin/ru/zveron/service/ProfilesFavoritesService.kt
> +            favoriteProfiles.addAll(
ага, это я не разглядел из браузера не очевидино было что это поле

2023-01-05 23:21 UTC, Schuyweiz approved these changes

2023-01-06 09:30 UTC, merged